version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: sikomplit-admin-prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: always
    env_file:
      - .env 