/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as dashboardIndexImport } from './routes/(dashboard)/index'
import { Route as authLogoutImport } from './routes/(auth)/logout'
import { Route as authLoginImport } from './routes/(auth)/login'
import { Route as dashboardUsersIndexImport } from './routes/(dashboard)/users/index'
import { Route as dashboardRecommendationsIndexImport } from './routes/(dashboard)/recommendations/index'
import { Route as dashboardRecommendationsIdImport } from './routes/(dashboard)/recommendations/$id'
import { Route as dashboardRecommendationsIdEditImport } from './routes/(dashboard)/recommendations/$id.edit'

// Create/Update Routes

const dashboardIndexRoute = dashboardIndexImport.update({
  id: '/(dashboard)/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const authLogoutRoute = authLogoutImport.update({
  id: '/(auth)/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const dashboardUsersIndexRoute = dashboardUsersIndexImport.update({
  id: '/(dashboard)/users/',
  path: '/users/',
  getParentRoute: () => rootRoute,
} as any)

const dashboardRecommendationsIndexRoute =
  dashboardRecommendationsIndexImport.update({
    id: '/(dashboard)/recommendations/',
    path: '/recommendations/',
    getParentRoute: () => rootRoute,
  } as any)

const dashboardRecommendationsIdRoute = dashboardRecommendationsIdImport.update(
  {
    id: '/(dashboard)/recommendations/$id',
    path: '/recommendations/$id',
    getParentRoute: () => rootRoute,
  } as any,
)

const dashboardRecommendationsIdEditRoute =
  dashboardRecommendationsIdEditImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => dashboardRecommendationsIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/logout': {
      id: '/(auth)/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof authLogoutImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)/': {
      id: '/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)/recommendations/$id': {
      id: '/(dashboard)/recommendations/$id'
      path: '/recommendations/$id'
      fullPath: '/recommendations/$id'
      preLoaderRoute: typeof dashboardRecommendationsIdImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)/recommendations/': {
      id: '/(dashboard)/recommendations/'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof dashboardRecommendationsIndexImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)/users/': {
      id: '/(dashboard)/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof dashboardUsersIndexImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)/recommendations/$id/edit': {
      id: '/(dashboard)/recommendations/$id/edit'
      path: '/edit'
      fullPath: '/recommendations/$id/edit'
      preLoaderRoute: typeof dashboardRecommendationsIdEditImport
      parentRoute: typeof dashboardRecommendationsIdImport
    }
  }
}

// Create and export the route tree

interface dashboardRecommendationsIdRouteChildren {
  dashboardRecommendationsIdEditRoute: typeof dashboardRecommendationsIdEditRoute
}

const dashboardRecommendationsIdRouteChildren: dashboardRecommendationsIdRouteChildren =
  {
    dashboardRecommendationsIdEditRoute: dashboardRecommendationsIdEditRoute,
  }

const dashboardRecommendationsIdRouteWithChildren =
  dashboardRecommendationsIdRoute._addFileChildren(
    dashboardRecommendationsIdRouteChildren,
  )

export interface FileRoutesByFullPath {
  '/login': typeof authLoginRoute
  '/logout': typeof authLogoutRoute
  '/': typeof dashboardIndexRoute
  '/recommendations/$id': typeof dashboardRecommendationsIdRouteWithChildren
  '/recommendations': typeof dashboardRecommendationsIndexRoute
  '/users': typeof dashboardUsersIndexRoute
  '/recommendations/$id/edit': typeof dashboardRecommendationsIdEditRoute
}

export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/logout': typeof authLogoutRoute
  '/': typeof dashboardIndexRoute
  '/recommendations/$id': typeof dashboardRecommendationsIdRouteWithChildren
  '/recommendations': typeof dashboardRecommendationsIndexRoute
  '/users': typeof dashboardUsersIndexRoute
  '/recommendations/$id/edit': typeof dashboardRecommendationsIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/logout': typeof authLogoutRoute
  '/(dashboard)/': typeof dashboardIndexRoute
  '/(dashboard)/recommendations/$id': typeof dashboardRecommendationsIdRouteWithChildren
  '/(dashboard)/recommendations/': typeof dashboardRecommendationsIndexRoute
  '/(dashboard)/users/': typeof dashboardUsersIndexRoute
  '/(dashboard)/recommendations/$id/edit': typeof dashboardRecommendationsIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/logout'
    | '/'
    | '/recommendations/$id'
    | '/recommendations'
    | '/users'
    | '/recommendations/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/logout'
    | '/'
    | '/recommendations/$id'
    | '/recommendations'
    | '/users'
    | '/recommendations/$id/edit'
  id:
    | '__root__'
    | '/(auth)/login'
    | '/(auth)/logout'
    | '/(dashboard)/'
    | '/(dashboard)/recommendations/$id'
    | '/(dashboard)/recommendations/'
    | '/(dashboard)/users/'
    | '/(dashboard)/recommendations/$id/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authLogoutRoute: typeof authLogoutRoute
  dashboardIndexRoute: typeof dashboardIndexRoute
  dashboardRecommendationsIdRoute: typeof dashboardRecommendationsIdRouteWithChildren
  dashboardRecommendationsIndexRoute: typeof dashboardRecommendationsIndexRoute
  dashboardUsersIndexRoute: typeof dashboardUsersIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  authLoginRoute: authLoginRoute,
  authLogoutRoute: authLogoutRoute,
  dashboardIndexRoute: dashboardIndexRoute,
  dashboardRecommendationsIdRoute: dashboardRecommendationsIdRouteWithChildren,
  dashboardRecommendationsIndexRoute: dashboardRecommendationsIndexRoute,
  dashboardUsersIndexRoute: dashboardUsersIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(auth)/login",
        "/(auth)/logout",
        "/(dashboard)/",
        "/(dashboard)/recommendations/$id",
        "/(dashboard)/recommendations/",
        "/(dashboard)/users/"
      ]
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx"
    },
    "/(auth)/logout": {
      "filePath": "(auth)/logout.tsx"
    },
    "/(dashboard)/": {
      "filePath": "(dashboard)/index.tsx"
    },
    "/(dashboard)/recommendations/$id": {
      "filePath": "(dashboard)/recommendations/$id.tsx",
      "children": [
        "/(dashboard)/recommendations/$id/edit"
      ]
    },
    "/(dashboard)/recommendations/": {
      "filePath": "(dashboard)/recommendations/index.tsx"
    },
    "/(dashboard)/users/": {
      "filePath": "(dashboard)/users/index.tsx"
    },
    "/(dashboard)/recommendations/$id/edit": {
      "filePath": "(dashboard)/recommendations/$id.edit.tsx",
      "parent": "/(dashboard)/recommendations/$id"
    }
  }
}
ROUTE_MANIFEST_END */
