name: Build and deploy Vite app to Azure Web App - sikomplitAdm

on:
  push:
    branches:
      - vite-version
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Add web.config for Azure App Service
        run: |
          echo ^<configuration^>^<system.webServer^>^<rewrite^>^<rules^>^<rule name="SPA" stopProcessing="true"^>^<match url=".*" /^>^<conditions logicalGrouping="MatchAll"^>^<add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" /^>^<add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" /^>^</conditions^>^<action type="Rewrite" url="/index.html" /^>^</rule^>^</rules^>^</rewrite^>^</system.webServer^>^</configuration^> > dist/web.config

      - name: Zip artifact for deployment
        run: |
          cd dist
          zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: release.zip

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sikomplitAdm'
          slot-name: 'Production'
          package: release.zip
          publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
