name: Build and deploy Vite app to Azure Web App - sikomplitAdm

on:
  push:
    branches:
      - vite-version
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: cd dist && zip -r ../release.zip . && cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: release.zip

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build

      - name: Unzip artifact for deployment
        run: unzip release.zip 

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sikomplitAdm'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
